export const Countries = [
  { currency: 'AED', symbol: 'AED', country: 'AED - UAE Dirham (AE)' },
  { currency: 'AFN', symbol: 'AFN', country: 'AFN - Afghani (AFN)' },
  { currency: 'ALL', symbol: 'Lek', country: 'ALL - Lek (Lek)' },
  { currency: 'AMD', symbol: 'AMD', country: 'AMD - Armenian Dram (AM)' },
  {
    currency: 'ANG',
    symbol: 'ƒ',
    country: 'ANG - Netherlands Antillian Guilder (ƒ)',
  },
  { currency: 'AOA', symbol: 'AOA', country: 'AOA - Kwanza (AOA)' },
  { currency: 'ARS', symbol: '$', country: 'ARS - Argentine Peso ($)' },
  { currency: 'AUD', symbol: '$', country: 'AUD - Australian Dollar ($)' },
  { currency: 'AWG', symbol: 'ƒ', country: 'AWG - Aruban Guilder (ƒ)' },
  {
    currency: 'AZN',
    symbol: 'AZN',
    country: 'AZN - Azerbaijanian Manat (AZN)',
  },
  { currency: 'BAM', symbol: 'KM', country: 'BAM - Convertible Marks (KM)' },
  { currency: 'BBD', symbol: '$', country: 'BBD - Barbados Dollar ($)' },
  { currency: 'BDT', symbol: 'BDT', country: 'BDT - Taka (BDT)' },
  { currency: 'BGN', symbol: 'BGN', country: 'BGN - Bulgarian Lev (BGN)' },
  { currency: 'BHD', symbol: 'BHD', country: 'BHD - Bahraini Dinar (BHD)' },
  { currency: 'BIF', symbol: 'BIF', country: 'BIF - Burundi Franc (BIF)' },
  {
    currency: 'BMD',
    symbol: '$',
    country: 'BMD - Bermudian Dollar (Bermuda Dollard $)',
  },
  { currency: 'BND', symbol: '$', country: 'BND - Brunei Dollar ($)' },
  { currency: 'BOB', symbol: '$b', country: 'BOB - Boliviano ($b)' },
  { currency: 'BOV', symbol: 'BOV', country: 'BOV - Mvdol (BOV)' },
  { currency: 'BRL', symbol: 'R$', country: 'BRL - Brazilian Real (R$)' },
  { currency: 'BSD', symbol: '$', country: 'BSD - Bahamian Dollar ($)' },
  { currency: 'BTC', symbol: 'BTC', country: 'BTC - Bitcoin (BTC)' },
  { currency: 'BTN', symbol: 'BTN', country: 'BTN - Ngultrum (BTN)' },
  { currency: 'BWP', symbol: 'P', country: 'BWP - Pula (P)' },
  { currency: 'BYR', symbol: 'p.', country: 'BYR - Belarussian Ruble (p.)' },
  { currency: 'BZD', symbol: 'BZ$', country: 'BZD - Belize Dollar (BZ$)' },
  { currency: 'CAD', symbol: '$', country: 'CAD - Canadian Dollar ($)' },
  { currency: 'CDF', symbol: 'CDF', country: 'CDF - Franc Congolais (CDF)' },
  { currency: 'CHE', symbol: 'CHE', country: 'CHE - WIR Euro (CHE)' },
  { currency: 'CHF', symbol: 'CHF', country: 'CHF - Swiss Franc (CHF)' },
  { currency: 'CHW', symbol: 'CHW', country: 'CHW - WIR Franc (CHW)' },
  {
    currency: 'CLF',
    symbol: 'CLF',
    country: 'CLF - Unidades de formento (CLF)',
  },
  { currency: 'CLP', symbol: '$', country: 'CLP - Chilean Peso ($)' },
  { currency: 'CNY', symbol: 'CNY', country: 'CNY - Yuan Renminbi (CNY)' },
  { currency: 'COP', symbol: '$', country: 'COP - Colombian Peso ($)' },
  {
    currency: 'COU',
    symbol: 'COU',
    country: 'COU - Unidad de Valor Real (COU)',
  },
  { currency: 'CRC', symbol: 'CRC', country: 'CRC - Costa Rican Colon (CRC)' },
  {
    currency: 'CUC',
    symbol: 'CUC$',
    country: 'CUC - Cuba Convertible Peso (CUC$)',
  },
  { currency: 'CUP', symbol: 'CUP', country: 'CUP - Cuban Peso (CUP)' },
  { currency: 'CVE', symbol: 'CVE', country: 'CVE - Cape Verde Escudo (CVE)' },
  { currency: 'CYP', symbol: 'CYP', country: 'CYP - Cyprus Pound (CYP)' },
  { currency: 'CZK', symbol: 'CZK', country: 'CZK - Czech Koruna (CZK)' },
  { currency: 'DJF', symbol: 'DJF', country: 'DJF - Djibouti Franc (DJF)' },
  { currency: 'DKK', symbol: 'kr', country: 'DKK - Danish Krone (kr)' },
  { currency: 'DOP', symbol: 'RD$', country: 'DOP - Dominican Peso (RD$)' },
  { currency: 'DZD', symbol: 'DZD', country: 'DZD - Algerian Dinar (DZD)' },
  { currency: 'EEK', symbol: 'kr', country: 'EEK - Kroon (kr)' },
  { currency: 'EGP', symbol: '£', country: 'EGP - Egyptian Pound (£)' },
  { currency: 'ERN', symbol: 'ERN', country: 'ERN - Nakfa (ERN)' },
  { currency: 'ETB', symbol: 'ETB', country: 'ETB - Ethiopian Birr (ETB)' },
  { currency: 'EUR', symbol: '€', country: 'EUR - Euro (€)' },
  { currency: 'FJD', symbol: '$', country: 'FJD - Fiji Dollar ($)' },
  {
    currency: 'FKP',
    symbol: '£',
    country: 'FKP - Falkland Islands Pound (£)',
  },
  { currency: 'GBP', symbol: '£', country: 'GBP - Pound Sterling (£)' },
  { currency: 'GEL', symbol: 'GEL', country: 'GEL - Lari (GEL)' },
  { currency: 'GGP', symbol: '£', country: 'GGP - Guernsey Pound (£)' },
  { currency: 'GHS', symbol: '¢', country: 'GHS - Cedi (¢)' },
  { currency: 'GIP', symbol: '£', country: 'GIP - Gibraltar Pound (£)' },
  { currency: 'GMD', symbol: 'GMD', country: 'GMD - Dalasi (GMD)' },
  { currency: 'GNF', symbol: 'GNF', country: 'GNF - Guinea Franc (GNF)' },
  { currency: 'GTQ', symbol: 'Q', country: 'GTQ - Quetzal (Q)' },
  {
    currency: 'GWP',
    symbol: 'GWP',
    country: 'GWP - Guinea-Bissau Peso (GWP)',
  },
  { currency: 'GYD', symbol: '$', country: 'GYD - Guyana Dollar ($)' },
  { currency: 'HKD', symbol: '元', country: 'HKD - Hong Kong Dollar (元)' },
  { currency: 'HNL', symbol: 'L', country: 'HNL - Lempira (L)' },
  { currency: 'HRK', symbol: 'kn', country: 'HRK - Croatian Kuna (kn)' },
  { currency: 'HTG', symbol: 'HTG', country: 'HTG - Gourde (HTG)' },
  { currency: 'HUF', symbol: 'Ft', country: 'HUF - Forint (Ft)' },
  { currency: 'IDR', symbol: 'Rp', country: 'IDR - Rupiah (Rp)' },
  {
    currency: 'ILS',
    symbol: 'ILS',
    country: 'ILS - New Israeli Sheqel (ILS)',
  },
  { currency: 'IMP', symbol: '£', country: 'IMP - Isle of Man Pound (£)' },
  { currency: 'INR', symbol: 'Rs.', country: 'INR - Indian Rupee (Rs.)' },
  { currency: 'IQD', symbol: 'IQD', country: 'IQD - Iraqi Dinar (IQD)' },
  { currency: 'IRR', symbol: 'IRR', country: 'IRR - Iranian Rial (IRR)' },
  { currency: 'ISK', symbol: 'kr', country: 'ISK - Iceland Krona (kr)' },
  { currency: 'JEP', symbol: '£', country: 'JEP - Jersey Pound (£)' },
  { currency: 'JMD', symbol: 'J$', country: 'JMD - Jamaican Dollar (J$)' },
  { currency: 'JOD', symbol: 'JOD', country: 'JOD - Jordanian Dinar (JOD)' },
  { currency: 'JPY', symbol: '¥', country: 'JPY - Yen (¥)' },
  { currency: 'KES', symbol: 'KES', country: 'KES - Kenyan Shilling (KES)' },
  { currency: 'KGS', symbol: 'KGS', country: 'KGS - Som (KGS)' },
  { currency: 'KHR', symbol: 'KHR', country: 'KHR - Riel (KHR)' },
  { currency: 'KMF', symbol: 'KMF', country: 'KMF - Comoro Franc (KMF)' },
  { currency: 'KPW', symbol: '₩', country: 'KPW - North Korean Won (₩)' },
  { currency: 'KRW', symbol: '₩', country: 'KRW - Won (₩)' },
  { currency: 'KWD', symbol: 'KWD', country: 'KWD - Kuwaiti Dinar (KWD)' },
  { currency: 'KYD', symbol: '$', country: 'KYD - Cayman Islands Dollar ($)' },
  { currency: 'KZT', symbol: 'KZT', country: 'KZT - Tenge (KZT)' },
  { currency: 'LAK', symbol: 'LAK', country: 'LAK - Kip (LAK)' },
  { currency: 'LBP', symbol: '£', country: 'LBP - Lebanese Pound (£)' },
  { currency: 'LKR', symbol: 'Rs', country: 'LKR - Sri Lanka Rupee (Rs)' },
  { currency: 'LRD', symbol: '$', country: 'LRD - Liberian Dollar ($)' },
  { currency: 'LSL', symbol: 'LSL', country: 'LSL - Loti (LSL)' },
  { currency: 'LTL', symbol: 'Lt', country: 'LTL - Lithuanian Litas (Lt)' },
  { currency: 'LVL', symbol: 'Ls', country: 'LVL - Latvian Lats (Ls)' },
  { currency: 'LYD', symbol: 'LYD', country: 'LYD - Libyan Dinar (LYD)' },
  { currency: 'MAD', symbol: 'MAD', country: 'MAD - Moroccan Dirham (MAD)' },
  { currency: 'MDL', symbol: 'MDL', country: 'MDL - Moldovan Leu (MDL)' },
  { currency: 'MGA', symbol: 'MGA', country: 'MGA - Malagascy Ariary (MGA)' },
  { currency: 'MKD', symbol: 'MKD', country: 'MKD - Denar (MKD)' },
  { currency: 'MMK', symbol: 'MMK', country: 'MMK - Kyat (MMK)' },
  { currency: 'MNT', symbol: 'MNT', country: 'MNT - Tugrik (MNT)' },
  { currency: 'MOP', symbol: 'MOP', country: 'MOP - Pataca (MOP)' },
  { currency: 'MRO', symbol: 'MRO', country: 'MRO - Ouguiya (MRO)' },
  { currency: 'MTL', symbol: 'MTL', country: 'MTL - Maltese Lira (MTL)' },
  { currency: 'MUR', symbol: 'Rp', country: 'MUR - Mauritius Rupee (Rp)' },
  { currency: 'MVR', symbol: 'MVR', country: 'MVR - Rufiyaa (MVR)' },
  { currency: 'MWK', symbol: 'MWK', country: 'MWK - Kwacha (MWK)' },
  { currency: 'MXN', symbol: '$', country: 'MXN - Mexican Peso ($)' },
  {
    currency: 'MXV',
    symbol: 'MXV',
    country: 'MXV - Mexican Unidad de Inversion (UIDd MXV)',
  },
  { currency: 'MYR', symbol: 'RM', country: 'MYR - Malaysian Ringgit (RM)' },
  { currency: 'MZN', symbol: 'MT', country: 'MZN - Metical (MT)' },
  { currency: 'NAD', symbol: '$', country: 'NAD - Namibian Dollar ($)' },
  { currency: 'NGN', symbol: 'NGN', country: 'NGN - Naira (NGN)' },
  { currency: 'NIO', symbol: 'C$', country: 'NIO - Cordoba Oro (C$)' },
  { currency: 'NOK', symbol: 'kr', country: 'NOK - Norwegian Krone (kr)' },
  { currency: 'NPR', symbol: 'Rp', country: 'NPR - Nepalese Rupee (Rp)' },
  { currency: 'NZD', symbol: '$', country: 'NZD - New Zealand Dollar ($)' },
  { currency: 'OMR', symbol: 'OMR', country: 'OMR - Rial Omani (OMR)' },
  { currency: 'PAB', symbol: 'B/.', country: 'PAB - Balboa (B/.)' },
  { currency: 'PEN', symbol: 'S/.', country: 'PEN - Nuevo Sol (S/.)' },
  { currency: 'PGK', symbol: 'PGK', country: 'PGK - Kina (PGK)' },
  { currency: 'PHP', symbol: 'Php', country: 'PHP - Philippine Peso (Php)' },
  { currency: 'PKR', symbol: 'Rs', country: 'PKR - Pakistan Rupee (Rs)' },
  { currency: 'PLN', symbol: 'PLN', country: 'PLN - Zloty (PLN)' },
  { currency: 'PYG', symbol: 'Gs', country: 'PYG - Guarani (Gs)' },
  { currency: 'QAR', symbol: 'QAR', country: 'QAR - Qatari Rial (QAR)' },
  { currency: 'ROL', symbol: 'ROL', country: 'ROL - Old Leu (ROL)' },
  { currency: 'RON', symbol: 'lei', country: 'RON - New Leu (lei)' },
  { currency: 'RSD', symbol: 'RSD', country: 'RSD - Serbian Dinar (RSD)' },
  { currency: 'RUB', symbol: 'RUB', country: 'RUB - Russian Ruble (RUB)' },
  { currency: 'RWF', symbol: 'RWF', country: 'RWF - Rwanda Franc (RWF)' },
  { currency: 'SAR', symbol: 'SAR', country: 'SAR - Saudi Riyal (SAR)' },
  {
    currency: 'SBD',
    symbol: '$',
    country: 'SBD - Solomon Islands Dollar ($)',
  },
  { currency: 'SCR', symbol: 'Rp', country: 'SCR - Seychelles Rupee (Rp)' },
  { currency: 'SDD', symbol: 'SDD', country: 'SDD - Sudanese Dinar (SDD)' },
  { currency: 'SDG', symbol: 'SDG', country: 'SDG - Sudanese Pound (SDG)' },
  { currency: 'SEK', symbol: 'kr', country: 'SEK - Swedish Krona (kr)' },
  { currency: 'SGD', symbol: '$', country: 'SGD - Singapore Dollar ($)' },
  { currency: 'SHP', symbol: '£', country: 'SHP - Saint Helena Pound (£)' },
  { currency: 'SIT', symbol: 'SIT', country: 'SIT - Tolar (SIT)' },
  { currency: 'SKK', symbol: 'SKK', country: 'SKK - Slovak Koruna (SKK)' },
  { currency: 'SLL', symbol: 'SLL', country: 'SLL - Leone (SLL)' },
  { currency: 'SOS', symbol: 'S', country: 'SOS - Somali Shilling (S)' },
  { currency: 'SRD', symbol: '$', country: 'SRD - Surinam Dollar ($)' },
  { currency: 'STD', symbol: 'STD', country: 'STD - Dobra (STD)' },
  { currency: 'SVC', symbol: '$', country: 'SVC - El Salvador Colon ($)' },
  { currency: 'SYP', symbol: '£', country: 'SYP - Syrian Pound (£)' },
  { currency: 'SZL', symbol: 'SZL', country: 'SZL - Lilangeni (SZL)' },
  { currency: 'THB', symbol: 'THB', country: 'THB - Baht (THB)' },
  { currency: 'TJS', symbol: 'TJS', country: 'TJS - Somoni (TJS)' },
  { currency: 'TMT', symbol: 'TMT', country: 'TMT - Manat (TMT)' },
  { currency: 'TND', symbol: 'TND', country: 'TND - Tunisian Dinar (TND)' },
  { currency: 'TOP', symbol: 'TOP', country: 'TOP - Paanga (TOP)' },
  { currency: 'TRL', symbol: 'TL', country: 'TRL - Turkish Lira (TL)' },
  { currency: 'TRY', symbol: 'YTL', country: 'TRY - New Turkish Lira (YTL)' },
  {
    currency: 'TTD',
    symbol: 'TT$',
    country: 'TTD - Trinidad and Tobago Dollar (TT$)',
  },
  { currency: 'TVD', symbol: '$', country: 'TVD - Tuvalu Dollar ($)' },
  { currency: 'TWD', symbol: 'NT$', country: 'TWD - New Taiwan Dollar (NT$)' },
  {
    currency: 'TZS',
    symbol: 'TZS',
    country: 'TZS - Tanzanian Shilling (TZS)',
  },
  { currency: 'UAH', symbol: 'UAH', country: 'UAH - Hryvnia (UAH)' },
  { currency: 'UGX', symbol: 'UGX', country: 'UGX - Uganda Shilling (UGX)' },
  { currency: 'USD', symbol: '$', country: 'USD - US Dollar ($)' },
  {
    currency: 'UYI',
    symbol: 'UYI',
    country: 'UYI - Uruguay Peso en Unidades Indexadas (UYI)',
  },
  { currency: 'UYU', symbol: '$U', country: 'UYU - Peso Uruguayo ($U)' },
  { currency: 'UZS', symbol: 'UZS', country: 'UZS - Uzbekistan Sum (UZS)' },
  { currency: 'VEB', symbol: 'VEB', country: 'VEB - Bolivar (VEB)' },
  { currency: 'VEF', symbol: 'VEF', country: 'VEF - Bolivar Fuerte (VEF)' },
  { currency: 'VND', symbol: 'VND', country: 'VND - Dong (VND)' },
  { currency: 'VUV', symbol: 'VUV', country: 'VUV - Vatu (VUV)' },
  { currency: 'WST', symbol: 'WST', country: 'WST - Tala (WST)' },
  { currency: 'XAF', symbol: 'XAF', country: 'XAF - CFA Franc BEAC (XAF)' },
  { currency: 'XCD', symbol: '$', country: 'XCD - East Caribbean Dollar ($)' },
  { currency: 'XDR', symbol: 'XDR', country: 'XDR - SDR (XDR)' },
  { currency: 'XOF', symbol: 'XOF', country: 'XOF - CFA Franc BCEAO (XOF)' },
  { currency: 'XPF', symbol: 'XPF', country: 'XPF - CFP Franc (XPF)' },
  { currency: 'YER', symbol: 'YER', country: 'YER - Yemeni Rial (YER)' },
  { currency: 'ZAR', symbol: 'R', country: 'ZAR - Rand (R)' },
  { currency: 'ZMK', symbol: 'ZMK', country: 'ZMK - Kwacha (ZMK)' },
  { currency: 'ZWD', symbol: 'Z$', country: 'ZWD - Zimbabwe Dollar (Z$)' },
];
