const Countries = [
  { currency: 'AED', symbol: 'AED', country: 'AED - UAE Dirham (AEDd)' },
  { currency: 'AFN', symbol: 'AFN', country: 'AFN - Afghani (AFNd)' },
  { currency: 'ALL', symbol: 'Lek', country: 'ALL - Lek (Lekd)' },
  { currency: 'AMD', symbol: 'AMD', country: 'AMD - Armenian Dram (AMDd)' },
  {
    currency: 'ANG',
    symbol: 'ƒ',
    country: 'ANG - Netherlands Antillian Guilder (ƒd)',
  },
  { currency: 'AOA', symbol: 'AOA', country: 'AOA - Kwanza (AOAd)' },
  { currency: 'ARS', symbol: '$', country: 'ARS - Argentine Peso ($d)' },
  { currency: 'AUD', symbol: '$', country: 'AUD - Australian Dollar ($d)' },
  { currency: 'AWG', symbol: 'ƒ', country: 'AWG - Aruban Guilder (ƒd)' },
  {
    currency: 'AZN',
    symbol: 'AZN',
    country: 'AZN - Azerbaijanian Manat (AZNd)',
  },
  { currency: 'BAM', symbol: 'KM', country: 'BAM - Convertible Marks (KMd)' },
  { currency: 'BBD', symbol: '$', country: 'BBD - Barbados Dollar ($d)' },
  { currency: 'BDT', symbol: 'BDT', country: 'BDT - Taka (BDTd)' },
  { currency: 'BGN', symbol: 'BGN', country: 'BGN - Bulgarian Lev (BGNd)' },
  { currency: 'BHD', symbol: 'BHD', country: 'BHD - Bahraini Dinar (BHDd)' },
  { currency: 'BIF', symbol: 'BIF', country: 'BIF - Burundi Franc (BIFd)' },
  {
    currency: 'BMD',
    symbol: '$',
    country: 'BMD - Bermudian Dollar (Bermuda Dollard $d)',
  },
  { currency: 'BND', symbol: '$', country: 'BND - Brunei Dollar ($d)' },
  { currency: 'BOB', symbol: '$b', country: 'BOB - Boliviano ($bd)' },
  { currency: 'BOV', symbol: 'BOV', country: 'BOV - Mvdol (BOVd)' },
  { currency: 'BRL', symbol: 'R$', country: 'BRL - Brazilian Real (R$d)' },
  { currency: 'BSD', symbol: '$', country: 'BSD - Bahamian Dollar ($d)' },
  { currency: 'BTC', symbol: 'BTC', country: 'BTC - Bitcoin (BTCd)' },
  { currency: 'BTN', symbol: 'BTN', country: 'BTN - Ngultrum (BTNd)' },
  { currency: 'BWP', symbol: 'P', country: 'BWP - Pula (Pd)' },
  { currency: 'BYR', symbol: 'p.', country: 'BYR - Belarussian Ruble (p.d)' },
  { currency: 'BZD', symbol: 'BZ$', country: 'BZD - Belize Dollar (BZ$d)' },
  { currency: 'CAD', symbol: '$', country: 'CAD - Canadian Dollar ($d)' },
  { currency: 'CDF', symbol: 'CDF', country: 'CDF - Franc Congolais (CDFd)' },
  { currency: 'CHE', symbol: 'CHE', country: 'CHE - WIR Euro (CHEd)' },
  { currency: 'CHF', symbol: 'CHF', country: 'CHF - Swiss Franc (CHFd)' },
  { currency: 'CHW', symbol: 'CHW', country: 'CHW - WIR Franc (CHWd)' },
  {
    currency: 'CLF',
    symbol: 'CLF',
    country: 'CLF - Unidades de formento (CLFd)',
  },
  { currency: 'CLP', symbol: '$', country: 'CLP - Chilean Peso ($d)' },
  { currency: 'CNY', symbol: 'CNY', country: 'CNY - Yuan Renminbi (CNYd)' },
  { currency: 'COP', symbol: '$', country: 'COP - Colombian Peso ($d)' },
  {
    currency: 'COU',
    symbol: 'COU',
    country: 'COU - Unidad de Valor Real (COUd)',
  },
  { currency: 'CRC', symbol: 'CRC', country: 'CRC - Costa Rican Colon (CRCd)' },
  {
    currency: 'CUC',
    symbol: 'CUC$',
    country: 'CUC - Cuba Convertible Peso (CUC$d)',
  },
  { currency: 'CUP', symbol: 'CUP', country: 'CUP - Cuban Peso (CUPd)' },
  { currency: 'CVE', symbol: 'CVE', country: 'CVE - Cape Verde Escudo (CVEd)' },
  { currency: 'CYP', symbol: 'CYP', country: 'CYP - Cyprus Pound (CYPd)' },
  { currency: 'CZK', symbol: 'CZK', country: 'CZK - Czech Koruna (CZKd)' },
  { currency: 'DJF', symbol: 'DJF', country: 'DJF - Djibouti Franc (DJFd)' },
  { currency: 'DKK', symbol: 'kr', country: 'DKK - Danish Krone (krd)' },
  { currency: 'DOP', symbol: 'RD$', country: 'DOP - Dominican Peso (RD$d)' },
  { currency: 'DZD', symbol: 'DZD', country: 'DZD - Algerian Dinar (DZDd)' },
  { currency: 'EEK', symbol: 'kr', country: 'EEK - Kroon (krd)' },
  { currency: 'EGP', symbol: '£', country: 'EGP - Egyptian Pound (£d)' },
  { currency: 'ERN', symbol: 'ERN', country: 'ERN - Nakfa (ERNd)' },
  { currency: 'ETB', symbol: 'ETB', country: 'ETB - Ethiopian Birr (ETBd)' },
  { currency: 'EUR', symbol: '€', country: 'EUR - Euro (€d)' },
  { currency: 'FJD', symbol: '$', country: 'FJD - Fiji Dollar ($d)' },
  {
    currency: 'FKP',
    symbol: '£',
    country: 'FKP - Falkland Islands Pound (£d)',
  },
  { currency: 'GBP', symbol: '£', country: 'GBP - Pound Sterling (£d)' },
  { currency: 'GEL', symbol: 'GEL', country: 'GEL - Lari (GELd)' },
  { currency: 'GGP', symbol: '£', country: 'GGP - Guernsey Pound (£d)' },
  { currency: 'GHS', symbol: '¢', country: 'GHS - Cedi (¢d)' },
  { currency: 'GIP', symbol: '£', country: 'GIP - Gibraltar Pound (£d)' },
  { currency: 'GMD', symbol: 'GMD', country: 'GMD - Dalasi (GMDd)' },
  { currency: 'GNF', symbol: 'GNF', country: 'GNF - Guinea Franc (GNFd)' },
  { currency: 'GTQ', symbol: 'Q', country: 'GTQ - Quetzal (Qd)' },
  {
    currency: 'GWP',
    symbol: 'GWP',
    country: 'GWP - Guinea-Bissau Peso (GWPd)',
  },
  { currency: 'GYD', symbol: '$', country: 'GYD - Guyana Dollar ($d)' },
  { currency: 'HKD', symbol: '元', country: 'HKD - Hong Kong Dollar (元d)' },
  { currency: 'HNL', symbol: 'L', country: 'HNL - Lempira (Ld)' },
  { currency: 'HRK', symbol: 'kn', country: 'HRK - Croatian Kuna (knd)' },
  { currency: 'HTG', symbol: 'HTG', country: 'HTG - Gourde (HTGd)' },
  { currency: 'HUF', symbol: 'Ft', country: 'HUF - Forint (Ftd)' },
  { currency: 'IDR', symbol: 'Rp', country: 'IDR - Rupiah (Rpd)' },
  {
    currency: 'ILS',
    symbol: 'ILS',
    country: 'ILS - New Israeli Sheqel (ILSd)',
  },
  { currency: 'IMP', symbol: '£', country: 'IMP - Isle of Man Pound (£d)' },
  { currency: 'INR', symbol: 'Rs.', country: 'INR - Indian Rupee (Rs.d)' },
  { currency: 'IQD', symbol: 'IQD', country: 'IQD - Iraqi Dinar (IQDd)' },
  { currency: 'IRR', symbol: 'IRR', country: 'IRR - Iranian Rial (IRRd)' },
  { currency: 'ISK', symbol: 'kr', country: 'ISK - Iceland Krona (krd)' },
  { currency: 'JEP', symbol: '£', country: 'JEP - Jersey Pound (£d)' },
  { currency: 'JMD', symbol: 'J$', country: 'JMD - Jamaican Dollar (J$d)' },
  { currency: 'JOD', symbol: 'JOD', country: 'JOD - Jordanian Dinar (JODd)' },
  { currency: 'JPY', symbol: '¥', country: 'JPY - Yen (¥d)' },
  { currency: 'KES', symbol: 'KES', country: 'KES - Kenyan Shilling (KESd)' },
  { currency: 'KGS', symbol: 'KGS', country: 'KGS - Som (KGSd)' },
  { currency: 'KHR', symbol: 'KHR', country: 'KHR - Riel (KHRd)' },
  { currency: 'KMF', symbol: 'KMF', country: 'KMF - Comoro Franc (KMFd)' },
  { currency: 'KPW', symbol: '₩', country: 'KPW - North Korean Won (₩d)' },
  { currency: 'KRW', symbol: '₩', country: 'KRW - Won (₩d)' },
  { currency: 'KWD', symbol: 'KWD', country: 'KWD - Kuwaiti Dinar (KWDd)' },
  { currency: 'KYD', symbol: '$', country: 'KYD - Cayman Islands Dollar ($d)' },
  { currency: 'KZT', symbol: 'KZT', country: 'KZT - Tenge (KZTd)' },
  { currency: 'LAK', symbol: 'LAK', country: 'LAK - Kip (LAKd)' },
  { currency: 'LBP', symbol: '£', country: 'LBP - Lebanese Pound (£d)' },
  { currency: 'LKR', symbol: 'Rs', country: 'LKR - Sri Lanka Rupee (Rsd)' },
  { currency: 'LRD', symbol: '$', country: 'LRD - Liberian Dollar ($d)' },
  { currency: 'LSL', symbol: 'LSL', country: 'LSL - Loti (LSLd)' },
  { currency: 'LTL', symbol: 'Lt', country: 'LTL - Lithuanian Litas (Ltd)' },
  { currency: 'LVL', symbol: 'Ls', country: 'LVL - Latvian Lats (Lsd)' },
  { currency: 'LYD', symbol: 'LYD', country: 'LYD - Libyan Dinar (LYDd)' },
  { currency: 'MAD', symbol: 'MAD', country: 'MAD - Moroccan Dirham (MADd)' },
  { currency: 'MDL', symbol: 'MDL', country: 'MDL - Moldovan Leu (MDLd)' },
  { currency: 'MGA', symbol: 'MGA', country: 'MGA - Malagascy Ariary (MGAd)' },
  { currency: 'MKD', symbol: 'MKD', country: 'MKD - Denar (MKDd)' },
  { currency: 'MMK', symbol: 'MMK', country: 'MMK - Kyat (MMKd)' },
  { currency: 'MNT', symbol: 'MNT', country: 'MNT - Tugrik (MNTd)' },
  { currency: 'MOP', symbol: 'MOP', country: 'MOP - Pataca (MOPd)' },
  { currency: 'MRO', symbol: 'MRO', country: 'MRO - Ouguiya (MROd)' },
  { currency: 'MTL', symbol: 'MTL', country: 'MTL - Maltese Lira (MTLd)' },
  { currency: 'MUR', symbol: 'Rp', country: 'MUR - Mauritius Rupee (Rpd)' },
  { currency: 'MVR', symbol: 'MVR', country: 'MVR - Rufiyaa (MVRd)' },
  { currency: 'MWK', symbol: 'MWK', country: 'MWK - Kwacha (MWKd)' },
  { currency: 'MXN', symbol: '$', country: 'MXN - Mexican Peso ($d)' },
  {
    currency: 'MXV',
    symbol: 'MXV',
    country: 'MXV - Mexican Unidad de Inversion (UIDd MXVd)',
  },
  { currency: 'MYR', symbol: 'RM', country: 'MYR - Malaysian Ringgit (RMd)' },
  { currency: 'MZN', symbol: 'MT', country: 'MZN - Metical (MTd)' },
  { currency: 'NAD', symbol: '$', country: 'NAD - Namibian Dollar ($d)' },
  { currency: 'NGN', symbol: 'NGN', country: 'NGN - Naira (NGNd)' },
  { currency: 'NIO', symbol: 'C$', country: 'NIO - Cordoba Oro (C$d)' },
  { currency: 'NOK', symbol: 'kr', country: 'NOK - Norwegian Krone (krd)' },
  { currency: 'NPR', symbol: 'Rp', country: 'NPR - Nepalese Rupee (Rpd)' },
  { currency: 'NZD', symbol: '$', country: 'NZD - New Zealand Dollar ($d)' },
  { currency: 'OMR', symbol: 'OMR', country: 'OMR - Rial Omani (OMRd)' },
  { currency: 'PAB', symbol: 'B/.', country: 'PAB - Balboa (B/.d)' },
  { currency: 'PEN', symbol: 'S/.', country: 'PEN - Nuevo Sol (S/.d)' },
  { currency: 'PGK', symbol: 'PGK', country: 'PGK - Kina (PGKd)' },
  { currency: 'PHP', symbol: 'Php', country: 'PHP - Philippine Peso (Phpd)' },
  { currency: 'PKR', symbol: 'Rs', country: 'PKR - Pakistan Rupee (Rsd)' },
  { currency: 'PLN', symbol: 'PLN', country: 'PLN - Zloty (PLNd)' },
  { currency: 'PYG', symbol: 'Gs', country: 'PYG - Guarani (Gsd)' },
  { currency: 'QAR', symbol: 'QAR', country: 'QAR - Qatari Rial (QARd)' },
  { currency: 'ROL', symbol: 'ROL', country: 'ROL - Old Leu (ROLd)' },
  { currency: 'RON', symbol: 'lei', country: 'RON - New Leu (leid)' },
  { currency: 'RSD', symbol: 'RSD', country: 'RSD - Serbian Dinar (RSDd)' },
  { currency: 'RUB', symbol: 'RUB', country: 'RUB - Russian Ruble (RUBd)' },
  { currency: 'RWF', symbol: 'RWF', country: 'RWF - Rwanda Franc (RWFd)' },
  { currency: 'SAR', symbol: 'SAR', country: 'SAR - Saudi Riyal (SARd)' },
  {
    currency: 'SBD',
    symbol: '$',
    country: 'SBD - Solomon Islands Dollar ($d)',
  },
  { currency: 'SCR', symbol: 'Rp', country: 'SCR - Seychelles Rupee (Rpd)' },
  { currency: 'SDD', symbol: 'SDD', country: 'SDD - Sudanese Dinar (SDDd)' },
  { currency: 'SDG', symbol: 'SDG', country: 'SDG - Sudanese Pound (SDGd)' },
  { currency: 'SEK', symbol: 'kr', country: 'SEK - Swedish Krona (krd)' },
  { currency: 'SGD', symbol: '$', country: 'SGD - Singapore Dollar ($d)' },
  { currency: 'SHP', symbol: '£', country: 'SHP - Saint Helena Pound (£d)' },
  { currency: 'SIT', symbol: 'SIT', country: 'SIT - Tolar (SITd)' },
  { currency: 'SKK', symbol: 'SKK', country: 'SKK - Slovak Koruna (SKKd)' },
  { currency: 'SLL', symbol: 'SLL', country: 'SLL - Leone (SLLd)' },
  { currency: 'SOS', symbol: 'S', country: 'SOS - Somali Shilling (Sd)' },
  { currency: 'SRD', symbol: '$', country: 'SRD - Surinam Dollar ($d)' },
  { currency: 'STD', symbol: 'STD', country: 'STD - Dobra (STDd)' },
  { currency: 'SVC', symbol: '$', country: 'SVC - El Salvador Colon ($d)' },
  { currency: 'SYP', symbol: '£', country: 'SYP - Syrian Pound (£d)' },
  { currency: 'SZL', symbol: 'SZL', country: 'SZL - Lilangeni (SZLd)' },
  { currency: 'THB', symbol: 'THB', country: 'THB - Baht (THBd)' },
  { currency: 'TJS', symbol: 'TJS', country: 'TJS - Somoni (TJSd)' },
  { currency: 'TMT', symbol: 'TMT', country: 'TMT - Manat (TMTd)' },
  { currency: 'TND', symbol: 'TND', country: 'TND - Tunisian Dinar (TNDd)' },
  { currency: 'TOP', symbol: 'TOP', country: 'TOP - Paanga (TOPd)' },
  { currency: 'TRL', symbol: 'TL', country: 'TRL - Turkish Lira (TLd)' },
  { currency: 'TRY', symbol: 'YTL', country: 'TRY - New Turkish Lira (YTLd)' },
  {
    currency: 'TTD',
    symbol: 'TT$',
    country: 'TTD - Trinidad and Tobago Dollar (TT$d)',
  },
  { currency: 'TVD', symbol: '$', country: 'TVD - Tuvalu Dollar ($d)' },
  { currency: 'TWD', symbol: 'NT$', country: 'TWD - New Taiwan Dollar (NT$d)' },
  {
    currency: 'TZS',
    symbol: 'TZS',
    country: 'TZS - Tanzanian Shilling (TZSd)',
  },
  { currency: 'UAH', symbol: 'UAH', country: 'UAH - Hryvnia (UAHd)' },
  { currency: 'UGX', symbol: 'UGX', country: 'UGX - Uganda Shilling (UGXd)' },
  { currency: 'USD', symbol: '$', country: 'USD - US Dollar ($d)' },
  {
    currency: 'UYI',
    symbol: 'UYI',
    country: 'UYI - Uruguay Peso en Unidades Indexadas (UYId)',
  },
  { currency: 'UYU', symbol: '$U', country: 'UYU - Peso Uruguayo ($Ud)' },
  { currency: 'UZS', symbol: 'UZS', country: 'UZS - Uzbekistan Sum (UZSd)' },
  { currency: 'VEB', symbol: 'VEB', country: 'VEB - Bolivar (VEBd)' },
  { currency: 'VEF', symbol: 'VEF', country: 'VEF - Bolivar Fuerte (VEFd)' },
  { currency: 'VND', symbol: 'VND', country: 'VND - Dong (VNDd)' },
  { currency: 'VUV', symbol: 'VUV', country: 'VUV - Vatu (VUVd)' },
  { currency: 'WST', symbol: 'WST', country: 'WST - Tala (WSTd)' },
  { currency: 'XAF', symbol: 'XAF', country: 'XAF - CFA Franc BEAC (XAFd)' },
  { currency: 'XCD', symbol: '$', country: 'XCD - East Caribbean Dollar ($d)' },
  { currency: 'XDR', symbol: 'XDR', country: 'XDR - SDR (XDRd)' },
  { currency: 'XOF', symbol: 'XOF', country: 'XOF - CFA Franc BCEAO (XOFd)' },
  { currency: 'XPF', symbol: 'XPF', country: 'XPF - CFP Franc (XPFd)' },
  { currency: 'YER', symbol: 'YER', country: 'YER - Yemeni Rial (YERd)' },
  { currency: 'ZAR', symbol: 'R', country: 'ZAR - Rand (Rd)' },
  { currency: 'ZMK', symbol: 'ZMK', country: 'ZMK - Kwacha (ZMKd)' },
  { currency: 'ZWD', symbol: 'Z$', country: 'ZWD - Zimbabwe Dollar (Z$d)' },
];
