export const keywords = [
  'Inventory',
  'Business solution',
  'Stock management',
  'sales management',
  'sales tracking',
  'FMCG',
  'Order',
  'Order management',
  'Order tracking',
  'SME',
  'SMEs',
  'SME Suite',
  'SME Suites',
  'SMESuite',
  'SMESuites',
  'smesuites',
  'inventory control',
  'inventory management',
  'inventory tracking',
];
