import type { Metadata } from 'next';
import { Forum, Lora } from 'next/font/google';
import './globals.css';
import { Menu } from './_components/Menu';
import { ThemeModeScript } from 'flowbite-react';
import { AppProvider } from './providers/app-provider';
import { Footer } from './(unauthorized)/_components/Footer';

const forum = Forum({
  style: ['normal'],
  weight: ['400'],
});

const lora = Lora({
  style: ['normal'],
  weight: ['400'],
  variable: '--font-lora',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lora.variable}`}>
      <head>
        <ThemeModeScript />
      </head>

      <body className={`${forum.style} ${forum.className} antialiased`}>
        <AppProvider>
          <>
            <Menu />
            {children}
          </>
        </AppProvider>
        <Footer />
      </body>
    </html>
  );
}
